### ISSUE TITLE
Target with the name "basket" cannot be found in the VectorDrawable to be animated

### ISSUE THREAD

**Issue by vinayaka7** [3llomi/RecordView#12]
Thanks for the Library but we have got issues in android Orio (Android Version 8). 
1. Click on Mike Icon and Recording is Working Fine.
2.Hold on Record button and swipe left to cancel and we got Exception in android 8 version. 

For Your Reference: 
java.lang.IllegalStateException: Target with the name "basket" cannot be found in the VectorDrawable to be animated.
        at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.prepareLocalAnimator(AnimatedVectorDrawable.java:839)
        at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.prepareLocalAnimators(AnimatedVectorDrawable.java:817)
        at android.graphics.drawable.AnimatedVectorDrawable.ensureAnimatorSet(AnimatedVectorDrawable.java:930)
        at android.graphics.drawable.AnimatedVectorDrawable.start(AnimatedVectorDrawable.java:914)
        at android.support.graphics.drawable.AnimatedVectorDrawableCompat.start(AnimatedVectorDrawableCompat.java:697)
        at com.devlomi.record_view.RecordView$1.onAnimationEnd(RecordView.java:145)
        at android.view.animation.Animation$3.run(Animation.java:382)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by 3llomi** [comment]
Hey @vinayaka7 ,
could you please post the Log?

**Comment by Duna** [comment]
the issue occurred when inside a library, and try to use within the app
