### ISSUE TITLE
Got NullPointerException when cancelled the recording 

### ISSUE THREAD

**Issue by Redman1037** [3llomi/RecordView#2]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                      at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.createRTAnimator(AnimatedVectorDrawable.java:1330)
                                      at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.parseAnimatorSet(AnimatedVectorDrawable.java:1288)
                                      at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.parseAnimatorSet(AnimatedVectorDrawable.java:1286)
                                      at android.graphics.drawable.AnimatedVectorDrawable$VectorDrawableAnimatorRT.init(AnimatedVectorDrawable.java:1255)
                                      at android.graphics.drawable.AnimatedVectorDrawable.ensureAnimatorSet(AnimatedVectorDrawable.java:919)
                                      at android.graphics.drawable.AnimatedVectorDrawable.start(AnimatedVectorDrawable.java:902)
                                      at android.support.graphics.drawable.AnimatedVectorDrawableCompat.start(AnimatedVectorDrawableCompat.java:697)
                                      at com.devlomi.record_view.RecordView$1.onAnimationEnd(RecordView.java:144)
                                      at android.view.animation.Animation$3.run(Animation.java:381)
                                      at android.os.Handler.handleCallback(Handler.java:751)
                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                      at android.os.Looper.loop(Looper.java:154)
                                      at android.app.ActivityThread.main(ActivityThread.java:6236)
                                      at java.lang.reflect.Method.invoke(Native Method)
                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by 3llomi** [comment]
@Redman1037 what Android API you are using?

**Comment by Redman1037** [comment]
API 25

**Comment by 3llomi** [comment]
@Redman1037 could you try Version `1.0beta`  and report back ?

**Comment by Redman1037** [comment]
I am getting exception only on Lenovo k4 note with custom rom installed . On other devices it is working fine

**Comment by 3llomi** [comment]
A new update has been published with some bug fixes.
please try to upgrade to latest version.

feel free to re-open this issue if you still have problems
