### ISSUE TITLE
Record view works fine on emulator but not on physical device

### ISSUE THREAD

**Issue by amnakashif** [3llomi/RecordView#69]
Hello everyone,

Record view works great on my android studio's emulator but whenever i try to record with my phone it provides "null" toast and doesn't record anything.

my emulator is running on API level 28.

whereas my physical device is Samsung A50. 
can anyone help please?

**Comment by amnakashif** [comment]
This is what my logcat shows: 

`2021-10-10 01:06:56.247 7637-24498/? E/MediaProvider: insertFileIfNecessary failed
    java.lang.IllegalArgumentException: Primary directory null not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
        at com.android.providers.media.MediaProvider.ensureFileColumns(MediaProvider.java:2932)
        at com.android.providers.media.MediaProvider.ensureUniqueFileColumns(MediaProvider.java:2597)
        at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:3291)
        at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3844)
        at com.android.providers.media.MediaProvider.insert(MediaProvider.java:3555)
        at com.android.providers.media.MediaProvider.insertFileForFuse(MediaProvider.java:7199)
        at com.android.providers.media.MediaProvider.insertFileIfNecessaryForFuse(MediaProvider.java:7293)
2021-10-10 01:06:56.273 4583-5094/? E/CoverManager: getCoverState : coverState is null
2021-10-10 01:06:56.294 4188-4188/? E/SecVibrator-HAL2.2_A: >> writeNode node:/timed_output/vibrator/enable val:0
2021-10-10 01:06:56.295 4188-4188/? E/SecVibrator-HAL2.2_A: << writeNode node OK 2
2021-10-10 01:06:56.296 4188-4188/? E/SecVibrator-HAL2.2_A: >> writeNode node:/timed_output/vibrator/enable val:100
2021-10-10 01:06:56.296 4188-4188/? E/SecVibrator-HAL2.2_A: << writeNode node OK 4
2021-10-10 01:06:56.307 4197-4539/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::acquire()
2021-10-10 01:06:56.328 4288-29704/? E/SEC_DRM_PLUGIN_Omafl: OmaPlugin::onOpenDecryptSession(fd)::Drm2IsDrmFileByExtFd::file is NOT DRM by extension
2021-10-10 01:06:56.396 4583-4583/? E/VibratorService: Vibration finished, cleaning up
2021-10-10 01:06:56.398 4188-4188/? E/SecVibrator-HAL2.2_A: >> writeNode node:/timed_output/vibrator/enable val:0
2021-10-10 01:06:56.399 4188-4188/? E/SecVibrator-HAL2.2_A: << writeNode node OK 2
2021-10-10 01:06:56.413 4138-4145/? E/statsd: Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->11038[I] (10)0x30000->AudioMix[S] 
2021-10-10 01:06:56.992 4138-4145/? E/statsd: Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->11038[I] (10)0x30000->AudioMix[S] 
2021-10-10 01:06:57.336 4288-27123/? E/SEC_DRM_PLUGIN_Omafl: OmaPlugin::onOpenDecryptSession(fd)::Drm2IsDrmFileByExtFd::file is NOT DRM by extension
2021-10-10 01:06:57.374 4138-4145/? E/statsd: Predicate 5980654721335871649 dropping data for dimension key (10)0x2010101->11038[I] (10)0x30000->AudioMix[S] 
2021-10-10 01:06:58.047 1381-1381/? E/DeXUtil: DesktopModeManager is null, so it can't be decided.`
