### ISSUE TITLE
Not working on android API level 17

### ISSUE THREAD

**Issue by ArisChoice** [3llomi/RecordView#7]
`android.view.InflateException: Binary XML file line #80: Error inflating class com.devlomi.record_view.RecordView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2282)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2340)
       at android.app.ActivityThread.access$800(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5293)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by 3llomi** [comment]
Could you please provide **XML**  that you are using?

**Comment by ArisChoice** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:gravity="center_vertical"
    android:orientation="horizontal">


    <LinearLayout
        android:id="@+id/messageFieldHolder"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:background="@color/white"
        android:gravity="center_vertical"
        android:orientation="horizontal"
        android:visibility="visible">

        <ImageView
            android:id="@+id/select_keyboard_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="@dimen/margin_1x"
            android:src="@drawable/ic_action_keyboard"
            android:visibility="gone" />

        <ImageView
            android:id="@+id/select_emoji_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="@dimen/margin_1x"
            android:src="@drawable/smiley" />

        <ImageView
            android:id="@+id/attachments_button"
            android:layout_width="@dimen/margin_3x"
            android:layout_height="@dimen/margin_3x"
            android:maxHeight="@dimen/margin_3x"
            android:maxWidth="@dimen/margin_3x"
            android:padding="@dimen/margin_.3x"
            android:src="@drawable/menu_icon_solid"
            android:visibility="visible" />

        <hani.momanii.supernova_emoji_library.Helper.EmojiconEditText
            android:id="@+id/message_Field"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:background="@color/white"
            android:hint="@string/write_something"
            android:maxHeight="@dimen/txt_8x"
            android:padding="@dimen/margin_.5x"
            android:textColorHint="@color/grey"
            android:textCursorDrawable="@drawable/custom_cursor" />


        


        <ImageView
            android:id="@+id/send_button"
            android:layout_width="@dimen/margin_3x"
            android:layout_height="@dimen/margin_3x"
            android:layout_marginLeft="@dimen/margin_.5x"
            android:padding="@dimen/margin_.5x"
            android:src="@drawable/send_ico"
            android:visibility="gone" />
    </LinearLayout>


    <com.devlomi.record_view.RecordView
        android:id="@+id/record_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_weight="1"
        android:visibility="gone"
        app:slide_to_cancel_arrow="@drawable/ic_keyboard_arrow_left"
        app:slide_to_cancel_text="Slide To Cancel" />

    <com.devlomi.record_view.RecordButton
        android:id="@+id/record_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentEnd="true"
        android:layout_centerVertical="true"
        android:background="@drawable/bg_mic"
        android:padding="@dimen/margin_.5x"
        android:scaleType="centerInside"
        android:visibility="visible"
        app:src="@drawable/ic_mic_white" />


</LinearLayout>
`

**Comment by 3llomi** [comment]
hmmm, that's weird ,i've already tried it on API 17 on Emulator and it works Fine.
can you try the **Sample app** and report back?

**Comment by ArisChoice** [comment]
I  created a  sample  app using your library. It is  working fine(in API level 17 too).  But it throwing above error in my current application(errror is  only below 19 API level devices). Don't know what is going wrong over here.

**Comment by 3llomi** [comment]
so the **Sample App** that is included in the library is working on your device on **API17** ,but it's not working with your app that you've created. is that right?

**Comment by vinayaka7** [comment]
In Android Api Level 19 .. Me too also facing the Same issue. 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kuku.namaste/com.kuku.namaste.ChatModule.ChatActivity}: android.view.InflateException: Binary XML file line #959: Error inflating class com.devlomi.record_view.RecordView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2264)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
        at android.app.ActivityThread.access$1100(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5336)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #959: Error inflating class com.devlomi.record_view.RecordView
        at android.view.LayoutInflater.createView(LayoutInflater.java:640)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:775)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:512)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:409)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:358)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.kuku.namaste.ChatModule.ChatActivity.onCreate(ChatActivity.java:408)
        at android.app.Activity.performCreate(Activity.java:5302)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5336) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at android.view.LayoutInflater.createView(LayoutInflater.java:614)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:775) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:512) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:409) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:358) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at com.kuku.namaste.ChatModule.ChatActivity.onCreate(ChatActivity.java:408) 
        at android.app.Activity.performCreate(Activity.java:5302) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5336) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xhdpi-v4/ic_delete.png from xml type xml resource ID #0x7f0808a2
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2420)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2375)
        at android.content.res.Resources.getXml(Resources.java:1029)
        at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:558)
        at android.support.graphics.drawable.AnimatedVectorDrawableCompat.inflate(AnimatedVectorDrawableCompat.java:458)
        at android.support.graphics.drawable.AnimatedVectorDrawableCompat.createFromXmlInner(AnimatedVectorDrawableCompat.java:250)
        at android.support.graphics.drawable.AnimatedVectorDrawableCompat.create(AnimatedVectorDrawableCompat.java:230)
        at com.devlomi.record_view.RecordView.init(RecordView.java:121)
        at com.devlomi.record_view.RecordView.<init>(RecordView.java:69)
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:775) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:512) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:409) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:358) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at com.kuku.namaste.ChatModule.ChatActivity.onCreate(ChatActivity.java:408) 
        at android.app.Activity.performCreate(Activity.java:5302) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5336) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.io.FileNotFoundException: Corrupt XML binary file
        at android.content.res.AssetManager.openXmlAssetNative(Native Method)
        at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:488)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2402)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2375) 
        at android.content.res.Resources.getXml(Resources.java:1029) 
        at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:558) 
        at android.support.graphics.drawable.AnimatedVectorDrawableCompat.inflate(AnimatedVectorDrawableCompat.java:458) 
        at android.support.graphics.drawable.AnimatedVectorDrawableCompat.createFromXmlInner(AnimatedVectorDrawableCompat.java:250) 
        at android.support.graphics.drawable.AnimatedVectorDrawableCompat.create(AnimatedVectorDrawableCompat.java:230) 
        at com.devlomi.record_view.RecordView.init(RecordView.java:121) 
        at com.devlomi.record_view.RecordView.<init>(RecordView.java:69) 
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:775) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:778) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:512) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:409) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:358) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at com.kuku.namaste.ChatModule.ChatActivity.onCreate(ChatActivity.java:408) 
        at android.app.Activity.performCreate(Activity.java:5302) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5336) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:873) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689) 
        at dalvik.system.NativeStart.main(Native Method)

**Comment by 3llomi** [comment]
Hey @vinayaka7  the problem is because you have the Drawable with the name `ic_delete` which is the same name of the **Vector Drawable** that included in the Library.
you can just rename the the drawable `ic_delete` that you have to another name ,until i push the new Update and change the name of it.

please try it and report back.

**Comment by 3llomi** [comment]
@vinayaka7  #6

**Comment by 3llomi** [comment]
@ArisChoice please try to upgrade `appcompat` library in your app to **V26** or higher since it has bug fixes for `AnimatedVectorDrawables` on older API's  

feel free to reopen this issue if the error still exists
