### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException 

### ISSUE THREAD

**Issue by Cool-Hackers-Tamil** [3llomi/RecordView#70]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void com.devlomi.record_view.RecordView.onActionDown(com.devlomi.record_view.RecordButton, android.view.MotionEvent)' on a null object reference
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.devlomi.record_view.RecordView.onActionDown(com.devlomi.record_view.RecordButton, android.view.MotionEvent)' on a null object reference
at com.devlomi.record_view.RecordButton.onTouch(RecordButton.java:105)
at android.view.View.dispatchTouchEvent(View.java:10058)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:435)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
at android.app.Activity.dispatchTouchEvent(Activity.java:3063)
at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:397)
at android.view.View.dispatchPointerEvent(View.java:10298)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4928)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4787)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4459)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4516)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6817)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6791)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6734)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6989)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
at android.os.MessageQueue.next(MessageQueue.java:328)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:6251)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

My Code I Used

private void initViewAudio(){
binding.recordButton.setRecordView(binding.recordView);
binding.recordView.setSoundEnabled(true);
binding.recordView.setShimmerEffectEnabled(true);
binding.recordView.setRecordButtonGrowingAnimationEnabled(true);

    binding.recordView.setCustomSounds(R.raw.record_start,R.raw.record_finished,R.raw.record_error);

    binding.recordButton.setListenForRecord(false);

    //ListenForRecord must be false ,otherwise onClick will not be called
    binding.recordButton.setOnRecordClickListener(new OnRecordClickListener() {
        @Override
        public void onClick(View v) {
            Toast.makeText(ChatActivity.this, "RECORD BUTTON CLICKED", Toast.LENGTH_SHORT).show();
            Log.d("RecordButton","RECORD BUTTON CLICKED");
        }
    });

    binding.recordView.setOnBasketAnimationEndListener(new OnBasketAnimationEnd() {
        @Override
        public void onAnimationEnd() {
            Log.d("RecordView", "Basket Animation Finished");
        }
    });

    binding.recordView.setRecordPermissionHandler(new RecordPermissionHandler() {
        @Override
        public boolean isPermissionGranted() {
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
                return true;
            }

            boolean recordPermissionAvailable = ContextCompat.checkSelfPermission(ChatActivity.this, Manifest.permission.RECORD_AUDIO) == PERMISSION_GRANTED;
            if (recordPermissionAvailable) {
                return true;
            }

            ActivityCompat.
                    requestPermissions(ChatActivity.this,
                            new String[]{Manifest.permission.RECORD_AUDIO},
                            0);

            return false;

        }
    });

    binding.recordView.setOnRecordListener(new OnRecordListener() {
        @Override
        public void onStart() {
            //Start Recording..

// Log.d("RecordView", "onStart");
setUpRecording();
try {
recorder.prepare();
} catch (IOException e) {
e.printStackTrace();
}
recorder.start();
binding.cardView.setVisibility(View.INVISIBLE);
binding.recordView.setVisibility(View.VISIBLE);

        }

        @Override
        public void onCancel() {
            //On Swipe To Cancel

// Log.d("RecordView", "onCancel");
recorder.reset();
recorder.release();
File file = new File(filename);
if (file.exists())
file.delete();
binding.recordView.setVisibility(View.GONE);
binding.messageLayout.setVisibility(View.VISIBLE);
}

        @Override
        public void onFinish(long recordTime, boolean limitReached) {
            //Stop Recording..
            //limitReached to determine if the Record was finished when time limit reached.

// String time = getHumanTimeText(recordTime);
Log.d("RecordView", "onFinish");
recorder.stop();
recorder.release();
// Log.d("RecordTime", time);
binding.recordView.setVisibility(View.GONE);
binding.messageLayout.setVisibility(View.VISIBLE);
}

        @Override
        public void onLessThanSecond() {
            //When the record time is less than One Second
            Log.d("RecordView", "onLessThanSecond");
            recorder.reset();
            recorder.release();
            File file = new File(filename);
            if (file.exists())
                file.delete();
            binding.recordView.setVisibility(View.GONE);
            binding.messageLayout.setVisibility(View.VISIBLE);
        }
    });

}

private void setUpRecording(){
    MediaRecorder recorder = new MediaRecorder();
    recorder.reset();
    recorder.setAudioSource(MediaRecorder.AudioSource.MIC);
    recorder.setOutputFormat(MediaRecorder.OutputFormat.THREE_GPP);
    recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);
    File file = new File(Environment.getExternalStorageDirectory().getAbsolutePath(),"MolaChat/Media/Recording");
    if (!file.exists())
        file.mkdirs();
    filename=file.getAbsolutePath() + File.separator + System.currentTimeMillis()+".3gp";
    recorder.setOutputFile(filename);

Please If This Is a Bug Please Fix Sir Or Any Mistake In My Code
Tell Me I am new For Coding And Making App Like Whatsapp

**Comment by 3llomi** [comment]
Please make sure to call
`recordButton.setRecordView(recordView)`

**Comment by Cool-Hackers-Tamil** [comment]
Thanks Bro it working now
